services:
  postgres:
    image: postgres:16
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - eventflow_pg_data:/var/lib/postgresql/data

volumes:
  eventflow_pg_data:
